<script setup>
import { useMyStore } from "~/store/store";

const store = useMyStore();
</script>

<template>
  <div class="legalContainer">
    <div class="legal-title">Legal & Compliance Settings</div>
    <div class="copyRightFrame">
      <div class="copyRightTitle">Copyright Disclaimer</div>
      <div class="copyRightText">
        This AI-powered doctor assistant provides general information based on
        the data provided. It is not intended to replace professional medical
        advice, diagnosis, or treatment. Always consult a qualified healthcare
        provider for medical concerns.
      </div>
    </div>
    <div class="copyRightFrame">
      <div class="copyRightTitle">Consultation Disclaimer</div>
      <div class="copyRightText">
        The prescriptions generated by
        {{ store.MediAssistConfigManager.DomainName }} are automatically
        captured from the conversation and are based on the information provided
        during the consultation.
      </div>
    </div>
    <div>
      <a href="/privacy-policy" target="_blank" class="privacy"
        >Privacy Policy</a
      >
      <span class="andText"> and </span>
      <a href="/terms-and-conditions" class="terms" target="_blank"
        >Terms and Conditions</a
      >
    </div>
  </div>
</template>

<style scoped>
@import "@/assets/css/components/settings/legal-compliance.css";
</style>