trigger:
  branches:
    include:
      - development

pr:
  branches:
    include:
      - development

pool:
  name: 'MEDI'

variables:
- group: mediclientui-dev-demo
- name: variableConfiguration

stages:
# - stage: "QualityTest"
#   jobs:
#   - job: Scanning
#     displayName: SonarQube
#     timeoutInMinutes: 360
#     cancelTimeoutInMinutes: 5
#     steps:
#     - task: SonarQubePrepare@7
#       inputs:
#         SonarQube: 'Sonarqube-API'
#         scannerMode: 'CLI'
#         configMode: 'manual'
#         cliProjectKey: 'Mediui-dev'
#         cliProjectName: 'Mediui-dev'
#         cliSources: '.'
#         extraProperties: |
#           sonar.coverage.exclusions=**/*
#           sonar.test.exclusions=**/*
#           sonar.qualitygate.wait=true
    
    # Configure for Pull Request analysis
    # - task: SonarQubePrepare@7
    #   condition: eq(variables['Build.Reason'], 'PullRequest')
    #   inputs:
    #     SonarQube: 'Sonarqube-API'
    #     scannerMode: 'CLI'
    #     configMode: 'manual'
    #     cliProjectKey: 'Mediui-dev'
    #     cliProjectName: 'Mediui-dev'
    #     cliSources: '.'
    #     extraProperties: |
    #       sonar.coverage.exclusions=**/*
    #       sonar.test.exclusions=**/*
    #       sonar.pullrequest.key=$(System.PullRequest.PullRequestNumber)
    #       sonar.pullrequest.branch=$(Build.SourceBranchName)
    #       sonar.pullrequest.base=development
    #       sonar.qualitygate.wait=true
    
    # # Configure for Branch analysis (manual runs, CI builds)
    # - task: SonarQubePrepare@7
    #   condition: ne(variables['Build.Reason'], 'PullRequest')
    #   inputs:
    #     SonarQube: 'Sonarqube-API'
    #     scannerMode: 'CLI'
    #     configMode: 'manual'
    #     cliProjectKey: 'Mediui-dev'
    #     cliProjectName: 'Mediui-dev'
    #     cliSources: '.'
    #     extraProperties: |
    #       sonar.coverage.exclusions=**/*
    #       sonar.test.exclusions=**/*
    #       sonar.branch.name=$(Build.SourceBranchName)
    #       sonar.qualitygate.wait=true
    
    # - task: SonarQubeAnalyze@7
    
    # - task: SonarQubePublish@7
    #   inputs:
    #     pollingTimeoutSec: '300'

- stage: "Build_Stage"
  jobs:
  - job: Build
    displayName: Build
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 5
    steps:
    - task: Docker@2
      inputs:
         containerRegistry: 'docker _Pits'
         repository: '$(dockerrepo)'
         command: 'build'
         Dockerfile: '**/dockerfile'
         arguments: ' --build-arg ASPNETCORE_ENVIRONMENT=Dev '
    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker _Pits'
        repository: '$(dockerrepo)'
        command: 'push'